apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: webtorrent-tracker
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "20"
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 2000
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/webtorrent-tracker:latest
        ports:
        - name: http1
          containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: WS_PORT
          value: "8000"
        resources:
          limits:
            cpu: "2"
            memory: "512Mi"
          requests:
            cpu: "1"
            memory: "256Mi"

